swagger: "2.0"

info:
  title: callAsap
  description: Emergency phone numbers
  version: "1.0"
  
host: 83.212.115.201

schemes:
  - http
  
produces:
  - application/json
  
basePath: /api.php

paths:
  /country:
    get:
      summary: Returns basic information for all the available countries
      description: |
        This URI is responsible for returning basic information for all the available countries
      responses:
        200:
          description: An array of countries with some basic info
          schema:
            type: array
            items:
              $ref: "#/definitions/country"
        500:
          description: Default error
          
          
definitions:
  country:
    type: object
    properties:
      ID:
        type: string
        description: Country's unique ID
      Name:
        type: string
        description: Country's name
      Languages:
        type: string
        description: Available languages (seperated by commas)
      Responsiveness:
        type: string
        description: How fast the calls are answered in seconds
      LastUpdate:
        type: string
        description: Last time data were modified
      SimNeeded112:
        type: string
        description: |
          The value is "yes" when sim is needed in order to make a call using 112. Otherwise, the value is "no"
      OnlyNumber:
        type: string
        description: |
          The value is "yes" when 112 is the only emergency number in the country. Otherwise, the value is "no"